<?php
namespace api\modules\v1\controllers;

use common\models\ApnsDevices;
use common\models\User;
use Yii;
use yii\base\Exception;
use yii\helpers\Json;
use yii\rest\Controller;
use paragraph1\phpFCM\Client;
use paragraph1\phpFCM\Notification;
use paragraph1\phpFCM\Recipient\Device;

class BaseApiController extends Controller
{
    var $language;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        switch (Yii::$app->request->getMethod()){
            case 'GET' :
                $this->language = Yii::$app->request->get('language_id');
                break;
            case 'POST' :
                $this->language = Yii::$app->request->post('language_id');
                break;
            default :
                $this->language = \Yii::$app->params['language_id'];
                break;
        }
        \Yii::$app->params['language_id'] = $this->language;
    }

    /**
     * @apiDefine AUTH
     * @apiHeader {String} AUTH_TOKEN Users unique access-key.
     * @apiParam {integer="en","ar"} language
     *
     * @apiHeaderExample {json} Header Example:
     *     {
     *       "AUTH_TOKEN": "[HASH]"
     *     }
     */

    /**
     * @apiDefine Response
     *
     * @apiSuccess {String} message success message
     * @apiSuccessExample Success-Response:
     *     HTTP/1.1 200 OK
     *     {
     *       "errorStatus" : false,
     *       "message" : "success message",
     *       "data" : {
     *          {"key" : "value"},
     *       }
     *     }
     *
     * @apiErrorExample Error-Response:
     *     HTTP/1.1 200 ok
     *     {
     *       "errorStatus": true,
     *       "code": error code,
     *       "message": "error message"
     *     }
     */

    // Members
    /**
     * Key which has to be in HTTP USERNAME and PASSWORD headers
     */
    Const APPLICATION_ID = 'ASCCPE';
    /** @var User $user */
    public $user;

    /**
     * Default response format
     * either 'json' or 'xml'
     */
    public function actionError()
    {
        $return_value = array("status" => false, "message" => "Action not found.");
        $this->_sendResponse(200, '{ "d" :' . json_encode($return_value) . '}');
    }

    public function render($view, $params = [])
    {
        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }

    function __clone()
    {
        // TODO: Implement __clone() method.
    }

    private $format = 'json';

    /**
     * @return array action filters
     */

    public function filters()
    {
        return array();
    }

    /**
     * Gets the message for a status code
     *
     * @param mixed $status
     * @access private
     * @return string
     */
    protected function _getStatusCodeMessage($status)
    {
// these could be stored in a .ini file and loaded
// via parse_ini_file()... however, this will suffice
// for an example
        $codes = Array(
            100 => 'Continue',
            101 => 'Switching Protocols',
            200 => 'OK',
            201 => 'Created',
            202 => 'Accepted',
            203 => 'Non-Authoritative Information',
            204 => 'No Content',
            205 => 'Reset Content',
            206 => 'Partial Content',
            300 => 'Multiple Choices',
            301 => 'Moved Permanently',
            302 => 'Found',
            303 => 'See Other',
            304 => 'Not Modified',
            305 => 'Use Proxy',
            306 => '(Unused)',
            307 => 'Temporary Redirect',
            400 => 'Bad Request',
            401 => 'Unauthorized',
            402 => 'Payment Required',
            403 => 'Forbidden',
            404 => 'Not Found',
            405 => 'Method Not Allowed',
            406 => 'Not Acceptable',
            407 => 'Proxy Authentication Required',
            408 => 'Request Timeout',
            409 => 'Conflict',
            410 => 'Gone',
            411 => 'Length Required',
            412 => 'Precondition Failed',
            413 => 'Request Entity Too Large',
            414 => 'Request-URI Too Long',
            415 => 'Unsupported Media Type',
            416 => 'Requested Range Not Satisfiable',
            417 => 'Expectation Failed',
            500 => 'Internal Server Error',
            501 => 'Not Implemented',
            502 => 'Bad Gateway',
            503 => 'Service Unavailable',
            504 => 'Gateway Timeout',
            505 => 'HTTP Version Not Supported'
        );
        return (isset($codes[$status])) ? $codes[$status] : '';
    }

    // helper functions

    /**
     * @param int $status
     * @param string $filePath
     * @param string $content_type
     */
    protected function _sendFileResponse($status = 200, $filePath = '', $content_type = 'application/pdf')
    {
        if (!empty($filePath)) {
            header("Content-type:$content_type");
            header('Content-Disposition: attachment; filename="' . basename($filePath) . '"');
            header('Content-Length: ' . filesize($filePath));
            readfile($filePath);
            Yii::$app->end($status, false);
        }
    }

    /**
     * @param string $body
     * @param string $message
     * @param int $isError
     */
    protected function _logResponse($body = [], $message = '', $http_status = 200)
    {
        $content_type = 'text/json';
        $status_header = 'HTTP/1.1 ' . $http_status . ' ' . $this->_getStatusCodeMessage($http_status);
        header($status_header);
        header('Content-type: ' . $content_type);

        if (!is_array($body)) {
            $body = array('message' => $body);
            $body = array_merge(array("status" => true), $body);
        }

        $body = Json::encode([
            "errorStatus" => false,
            "data" => $body,
            "timestamp" => time(),
            'message' => $message
        ]);


        Yii::$app->end($http_status, false);
    }

    /**
     * @param string $body
     * @param string $message
     * @param int $isError
     */
    protected function _sendResponse($body = [], $message = '', $http_status = 200)
    {
        $content_type = 'text/json';
        $status_header = 'HTTP/1.1 ' . $http_status . ' ' . $this->_getStatusCodeMessage($http_status);
        header($status_header);
        header('Content-type: ' . $content_type);

        if (!is_array($body)) {
            $body = array('message' => $body);
            $body = array_merge(array("status" => true), $body);
        }

        $body = Json::encode([
            "status" => false,
            "data" => $body,
            "timestamp" => time(),
           // "language" => $this->region,
            'message' => $message
        ]);


        echo $body;die();
        Yii::$app->end($http_status, false);
    }

    /**
     * @param int $status
     * @param mixed $customMessage
     * @param mixed $errorCode
     * @param string $contentType
     */
    protected function _sendErrorResponse($status = 400, $customMessage = null, $errorCode = null, $contentType = 'text/json')
    {
        $message = $this->_getStatusCodeMessage($status);
        $status_header = 'HTTP/1.1 ' . $status . ' ' . $this->_getStatusCodeMessage($status);

        if ($customMessage !== null) {
            $message .= ". " . $customMessage;
        }

        header($status_header);
        header('Content-type: ' . $contentType);

        if ($errorCode === null) {
            $code = $status;
        } else {
            $message = $customMessage;
            $code = $errorCode;
        }

        $body = Json::encode(
            array(
                "status" => true,
                "code" => $code,
                'message' => $message
            )
        );

        echo $body;die();
        Yii::getLogger()->log("code: $code, message: $message", 'error');

       // Yii::$app->end($status, false);
    }

    protected function _checkAuth()
    {
        if (!isset($_SERVER['HTTP_AUTH_TOKEN'])) {
            // Error: Unauthorized
            $this->_sendErrorResponse(401);
        }

        try {
            $token = $_SERVER['HTTP_AUTH_TOKEN'];
            $this->user = User::findIdentityByAuthKey($token);
            if ($this->user == null) {
                $this->_sendErrorResponse(401);
            }

            /*if ($this->user->status == User::STATUS_DELETED) {
                $this->_sendErrorResponse(423, "The user is banned.");
            }*/

            return $this->user;
        } catch (Exception $e) {
            $this->_sendErrorResponse(400);
        }
        return false;
    }


    protected function _checkEmail()
    {
        try {
            if (!isset($this->user)) {
                // Error: Unauthorized
                $this->_sendErrorResponse(401);
            }
            if (!$this->user->isEmailActive()) {
                $this->_sendErrorResponse(403); //"To enjoy the full ViRVi experience, please activate your account by clicking on the link sent to your email address:"
            }
            return true;
        } catch (Exception $e) {
            $this->_sendErrorResponse(400);
        }
        return false;
    }

    /**
     * Generates new token
     */
    protected function _generateToken()
    {
        return Yii::$app->security->generateRandomString() . '_' . time();
    }

    protected function _getUserID()
    {
        $token = $_SERVER['HTTP_AUTH_TOKEN'];

        return $this->_getTokenCache($token);
    }

//    protected function _getTokenByUserID($userID) {
//        return $this->_getTokenCache($userID);
//    }

    protected function _userData(User $user)
    {
        $data = $user->toArray();

               /*
         * Remove fbId from data for security purposes
         */
        unset($data['auth_key']);
        unset($data['access_token']);
        unset($data['password_hash']);
        unset($data['activate_token']);
        unset($data['password_reset_token']);
        unset($data['google_id']);
        unset($data['facebook_id']);
        unset($data['verification_token']);
        return $data;
    }

    protected function _saveTokenCache1($id)
    {
        $cache = Yii::$app->cache;
        $token = $this->_generateToken();
        $cache->set($token, $id, 0);
        return $token;
    }

    protected function _getTokenCache($token)
    {
        $cache = Yii::$app->cache;
        return $cache->get($token);
    }

    protected function _getToken()
    {
        return $_SERVER['HTTP_AUTH_TOKEN'];
    }

    protected function convertToArray($objectList)
    {
        $response = array();

        foreach ($objectList as $object) {
            $response[] = $object;
        }
        return $response;
    }

    /**
     * @param string $name
     * @param array $params
     * @return mixed
     */
    public function __call($name, $params)
    {
        return parent::__call($name, $params); // TODO: Change the autogenerated stub
    }
    public function notification($message, $touserid, $type,$reference_id ,$payload = null) {
//        $payload['tone'] = "tone1.wav";

        /** @var ApnsDevices $apns */
        $toObjUser = User::findByPk($touserid);
        $fromObjUser = User::findByPk($payload['from_id']);
        $apiKey = Yii::$app->params['apikey'];
        $stat = "";

        $apns = ApnsDevices::find()->where(['user_id' => $toObjUser->id])->asArray()->all();
        // print_r($payload['message']);die;
        $payload = $this->fillNullArr($payload);

        if (!empty($apns)) {

            $date = date('Y-m-d h:i:s', time());
            foreach ($apns as $apn){
                $device_token = $apn['device_token'];
                if(!empty($device_token)){
                    $client = new Client();
                    $client->setApiKey($apiKey);
                    $client->injectHttpClient(new \GuzzleHttp\Client());
                    $note = new Notification($message, $payload['message']);
                    $note->setIcon('notification_icon_resource_name')
                        ->setColor('#ffffff')
                        ->setBadge(1);

                    $objMessage = new \paragraph1\phpFCM\Message();
                    $objMessage->addRecipient(new Device($device_token));

                    $objMessage->setNotification($note)
                        ->setData($payload);

                    $response = $client->send($objMessage);

                    // print_r($response);die;

                    /* if ($response->getStatusCode() == 200) {
                         $stat = ApnsMessages::STATUS_DELIVERED;
                     } else {
                         $stat = ApnsMessages::STATUS_FAILED;
                     }*/
                }
            }

            $array = json_encode($payload);
            $apnsMessage = new \common\models\Notification;
            $apnsMessage->from_id = $fromObjUser->id;
            $apnsMessage->reference_id = $reference_id;
            $apnsMessage->to_id = $toObjUser->id;
            $apnsMessage->message = $payload['message'];
            $apnsMessage->fk_device_id = $apn['id'];
            $apnsMessage->type =$type;
            $apnsMessage->created_at =date('Y-m-d H:i:s');
            $apnsMessage->updated_at = date('Y-m-d H:i:s');
            //   $apnsMessage->delivered_at = $date;
            //  $apnsMessage->status = $stat;
            $apnsMessage->json_data = $array;
            $apnsMessage->save(false);


//            file_put_contents("reqLog.txt",print_r([$apns->device_token, $message,$payload], true));
        }
    }
    public function fillNullArr($value) {

        $ar = array_replace($value, array_fill_keys(
                array_keys($value, null), ""
            )
        );

        return $ar;
    }
}
